export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type OperationKind = "list" | "get" | "create" | "update" | "delete";

export type RouteOperation = {
  kind: OperationKind;
  method: HttpMethod;
  /** App-router segment path under the generated API root, e.g. `[id]` or empty for collection. */
  segmentPath: string;
  /** OpenAPI path suffix after `/generated/{slug}`. */
  openApiSuffix: string;
  description: string;
  summary: string;
  hasQuery: boolean;
  hasBody: boolean;
  hasPathParams: boolean;
  responseType: "entity" | "list" | "empty";
  responseSet: "public" | "common" | "auth" | "crud";
  auth: boolean;
};

export type ResourceDefinition = {
  name: string;
  slug: string;
  tag: string;
  tableName: string;
  nested?: {
    parentSlug: string;
    parentParam: string;
  };
};

export const GENERATED_HEADER =
  "// @generated by scripts/generate-scale-fixtures.mts — do not edit\n";

export const SCALE_RESOURCES: ResourceDefinition[] = [
  { name: "Customer", slug: "customers", tag: "Customers", tableName: "customers" },
  { name: "Invoice", slug: "invoices", tag: "Invoices", tableName: "invoices" },
  {
    name: "Project",
    slug: "projects",
    tag: "Projects",
    tableName: "projects",
    nested: { parentSlug: "organizations", parentParam: "organizationId" },
  },
  {
    name: "Task",
    slug: "tasks",
    tag: "Tasks",
    tableName: "tasks",
    nested: { parentSlug: "projects", parentParam: "projectId" },
  },
  { name: "Subscription", slug: "subscriptions", tag: "Subscriptions", tableName: "subscriptions" },
  { name: "Webhook", slug: "webhooks", tag: "Webhooks", tableName: "webhooks" },
  { name: "Team", slug: "teams", tag: "Teams", tableName: "teams" },
  { name: "Member", slug: "members", tag: "Members", tableName: "members" },
  { name: "Product", slug: "products", tag: "Products", tableName: "products" },
  { name: "Order", slug: "orders", tag: "Orders", tableName: "orders" },
  { name: "Payment", slug: "payments", tag: "Payments", tableName: "payments" },
  { name: "Refund", slug: "refunds", tag: "Refunds", tableName: "refunds" },
  { name: "Notification", slug: "notifications", tag: "Notifications", tableName: "notifications" },
  { name: "Report", slug: "reports", tag: "Reports", tableName: "reports" },
  { name: "Export", slug: "exports", tag: "Exports", tableName: "exports" },
  { name: "Session", slug: "sessions", tag: "Sessions", tableName: "sessions" },
  { name: "ApiKey", slug: "api-keys", tag: "ApiKeys", tableName: "api_keys" },
  { name: "AuditLog", slug: "audit-logs", tag: "AuditLogs", tableName: "audit_logs" },
  { name: "CatalogItem", slug: "catalog-items", tag: "Catalog", tableName: "catalog_items" },
  { name: "Workspace", slug: "workspaces", tag: "Workspaces", tableName: "workspaces" },
  { name: "Organization", slug: "organizations", tag: "Organizations", tableName: "organizations" },
  { name: "Department", slug: "departments", tag: "Departments", tableName: "departments" },
  { name: "Document", slug: "documents", tag: "Documents", tableName: "documents" },
  { name: "Comment", slug: "comments", tag: "Comments", tableName: "comments" },
  { name: "Attachment", slug: "attachments", tag: "Attachments", tableName: "attachments" },
];

export function getResourceOperations(resource: ResourceDefinition): RouteOperation[] {
  return [
    {
      kind: "list",
      method: "GET",
      segmentPath: "",
      openApiSuffix: "",
      summary: `List ${resource.slug}`,
      description: `Returns a paginated list of ${resource.slug}`,
      hasQuery: true,
      hasBody: false,
      hasPathParams: false,
      responseType: "list",
      responseSet: "public",
      auth: false,
    },
    {
      kind: "get",
      method: "GET",
      segmentPath: "[id]",
      openApiSuffix: "/{id}",
      summary: `Get ${resource.name.toLowerCase()} by ID`,
      description: `Returns a single ${resource.name.toLowerCase()} by identifier`,
      hasQuery: false,
      hasBody: false,
      hasPathParams: true,
      responseType: "entity",
      responseSet: "common",
      auth: true,
    },
    {
      kind: "create",
      method: "POST",
      segmentPath: "",
      openApiSuffix: "",
      summary: `Create ${resource.name.toLowerCase()}`,
      description: `Creates a new ${resource.name.toLowerCase()}`,
      hasQuery: false,
      hasBody: true,
      hasPathParams: false,
      responseType: "entity",
      responseSet: "crud",
      auth: true,
    },
    {
      kind: "update",
      method: "PATCH",
      segmentPath: "[id]",
      openApiSuffix: "/{id}",
      summary: `Update ${resource.name.toLowerCase()}`,
      description: `Updates an existing ${resource.name.toLowerCase()}`,
      hasQuery: false,
      hasBody: true,
      hasPathParams: true,
      responseType: "entity",
      responseSet: "auth",
      auth: true,
    },
    {
      kind: "delete",
      method: "DELETE",
      segmentPath: "[id]",
      openApiSuffix: "/{id}",
      summary: `Delete ${resource.name.toLowerCase()}`,
      description: `Deletes a ${resource.name.toLowerCase()} by identifier`,
      hasQuery: false,
      hasBody: false,
      hasPathParams: true,
      responseType: "empty",
      responseSet: "auth",
      auth: true,
    },
  ];
}

export function getSchemaNames(resource: ResourceDefinition) {
  return {
    entity: `${resource.name}Entity`,
    listResponse: `${resource.name}ListResponse`,
    idParams: `${resource.name}IdParams`,
    collectionPathParams: `${resource.name}CollectionPathParams`,
    listQuery: `${resource.name}ListQuery`,
    createInput: `Create${resource.name}Input`,
    updateInput: `Update${resource.name}Input`,
    zodEntity: `${resource.name}Schema`,
    zodCreate: `Create${resource.name}Schema`,
    zodUpdate: `Update${resource.name}Schema`,
    zodIdParams: `${resource.name}IdParamsSchema`,
    zodCollectionPathParams: `${resource.name}CollectionPathParamsSchema`,
    zodListQuery: `${resource.name}ListQuerySchema`,
  };
}

export function getPathParamsTypeName(
  resource: ResourceDefinition,
  operation: RouteOperation,
): string | null {
  const names = getSchemaNames(resource);
  if (resource.nested) {
    return operation.hasPathParams ? names.idParams : names.collectionPathParams;
  }
  return operation.hasPathParams ? names.idParams : null;
}

export function getOperationId(
  resource: ResourceDefinition,
  operation: RouteOperation,
  prefix: string,
): string {
  const action =
    operation.kind === "list"
      ? "List"
      : operation.kind === "get"
        ? "Get"
        : operation.kind === "create"
          ? "Create"
          : operation.kind === "update"
            ? "Update"
            : "Delete";
  return `${prefix}${action}${resource.name}`;
}

export function getOpenApiPath(resource: ResourceDefinition, operation: RouteOperation): string {
  const base = resource.nested
    ? `/generated/${resource.nested.parentSlug}/{${resource.nested.parentParam}}/${resource.slug}`
    : `/generated/${resource.slug}`;
  return `${base}${operation.openApiSuffix}`;
}

export function getRouteBaseSegments(resource: ResourceDefinition, routeRoot: string): string[] {
  if (resource.nested) {
    return [
      routeRoot,
      "generated",
      resource.nested.parentSlug,
      `[${resource.nested.parentParam}]`,
      resource.slug,
    ];
  }
  return [routeRoot, "generated", resource.slug];
}

export function getTotalRouteCount(): number {
  return SCALE_RESOURCES.reduce(
    (count, resource) => count + getResourceOperations(resource).length,
    0,
  );
}

export function getResourceOperationsForFramework(
  resource: ResourceDefinition,
  framework: "next-app-router" | "next-pages-router" | "tanstack" | "react-router",
): RouteOperation[] {
  const operations = getResourceOperations(resource);
  if (framework === "tanstack" || framework === "react-router") {
    return operations
      .filter((operation) => operation.kind !== "delete")
      .map((operation) =>
        operation.kind === "update"
          ? {
              ...operation,
              method: "POST",
            }
          : operation,
      );
  }
  return operations;
}
