// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api-docs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api-docs";
  };
  "routes/api-docs.tsx": {
    id: "routes/api-docs";
    page: "/api-docs";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  root: typeof import("./src/root.tsx");
  "routes/api-docs": typeof import("./src/routes/api-docs.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
};
